/* Calculator APP */
const ac = document.getElementById("ac");
const del = document.getElementById("del");
const div = document.getElementById("div");
const one = document.getElementById("one");
const two = document.getElementById("two");
const three = document.getElementById("three");
const mul = document.getElementById("mul");
const four = document.getElementById("four");
const five = document.getElementById("five");
const six = document.getElementById("six");
const sum = document.getElementById("sum");
const seven = document.getElementById("seven");
const eight = document.getElementById("eight");
const nine = document.getElementById("nine");
const min = document.getElementById("min");
const period = document.getElementById("period");
const result = document.getElementById("zero");
